export const ERP_CONSTANTS = {
  DONOR_TYPES: ["individual", "corporate", "trust", "foundation"] as const,
  DONATION_MODES: ["cash", "bank", "upi", "cheque", "online"] as const,
  FUNDS: [
    "General",
    "PEP",
    "MAGIC Youth",
    "MuST",
    "Summer Shapes",
    "Scholar Support Programme",
    "JoY Desk",
    "VIP",
    "Compassion Connect",
    "STHRI",
    "O GOD",
    "MAGIS",
    "Each One Teach Ten",
    "Y HUB",
  ] as const,
  BUDGET_CATEGORIES: [
    "Program Activities",
    "Materials & Supplies",
    "Travel",
    "Venue & Logistics",
    "Honorariums",
    "Salaries & Staff",
    "Admin & Overhead",
    "Communication & Marketing",
    "Training & Capacity Building",
    "Scholarships & Aid",
  ] as const,
  EXPENSE_PAYMENT_MODES: ["cash", "bank", "upi", "cheque", "online"] as const,
  CURRENCIES: ["INR", "USD", "EUR", "GBP", "AED"] as const,
  VOLUNTEER_GENDERS: ["male", "female", "other"] as const,
  VOLUNTEER_AVAILABILITY: ["weekdays", "weekends", "evenings", "flexible", "full-time"] as const,
  VOLUNTEER_STATUSES: ["active", "inactive"] as const,
  VOLUNTEER_ACTIVITY_TYPES: [
    "Program Support",
    "Event Setup",
    "Training",
    "Outreach",
    "Administrative",
    "Field Work",
    "Fundraising",
    "Content & Media",
    "Other",
  ] as const,
  ASSET_CATEGORIES: [
    "Electronics & IT",
    "Furniture",
    "Office Equipment",
    "Vehicles",
    "Audio-Visual",
    "Sports Equipment",
    "Kitchen Equipment",
    "Books & Library",
    "Other",
  ] as const,
  ASSET_CONDITIONS: ["new", "good", "fair", "poor"] as const,
  ASSET_STATUSES: ["in-use", "in-stock", "maintenance", "disposed"] as const,
  INVENTORY_CATEGORIES: [
    "Stationery",
    "Materials & Supplies",
    "Merchandise",
    "Food & Beverage",
    "Printing",
    "Tools & Equipment",
    "Other",
  ] as const,
  INVENTORY_UNITS: ["pieces", "boxes", "sets", "kgs", "litres", "rolls", "packs", "metres"] as const,
  STAFF_DEPARTMENTS: ["Leadership", "Programs", "Operations", "Finance & Admin", "Communications", "Outreach", "Volunteer Coordination", "Field Staff", "Other"] as const,
  STAFF_EMPLOYMENT_TYPES: ["full-time", "part-time", "contract", "volunteer"] as const,
  STAFF_STATUSES: ["active", "on-leave", "resigned"] as const,
  ATTENDANCE_STATUSES: ["present", "absent", "half-day", "leave"] as const,
  LEAVE_TYPES: ["casual", "sick", "annual", "unpaid", "other"] as const,
  LEAVE_STATUSES: ["pending", "approved", "rejected"] as const,
  BENEFICIARY_GENDERS: ["male", "female", "other"] as const,
  BENEFICIARY_CATEGORIES: ["student", "child", "elder", "woman", "differently-abled", "family", "youth", "other"] as const,
  BENEFICIARY_PROGRAMS: [
    "PEP",
    "MAGIC Youth",
    "MuST",
    "Summer Shapes",
    "Scholar Support Programme",
    "Compassion Connect",
    "STHRI",
    "O GOD",
    "MAGIS",
    "Each One Teach Ten",
    "Y HUB",
    "General",
  ] as const,
  BENEFICIARY_STATUSES: ["active", "inactive", "graduated", "closed"] as const,
  SERVICE_TYPES: [
    "Education Support",
    "Healthcare",
    "Nutrition",
    "Skill Training",
    "Financial Aid",
    "Material Support",
    "Counseling",
    "Scholarship",
    "Other",
  ] as const,
}

export function currentFiscalYear(): string {
  const now = new Date()
  const year = now.getFullYear()
  const month = now.getMonth() + 1
  if (month >= 4) {
    return `${year}-${year + 1}`
  }
  return `${year - 1}-${year}`
}